name: Publish

on:
  push:
    branches:
      - master

env:
#  SERVER_WORK_DIR: /root/zingoweb/production
  IMAGE_NAME: ghcr.io/$(echo '${{github.REPOSITORY}}/${{github.ref_name}}:latest' | tr '[:upper:]' '[:lower:]')

jobs:
  Publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checking out
        uses: actions/checkout@v4.1.7
      - name: Build
        run: docker image build -f ./Dockerfile -t ${{env.IMAGE_NAME}} .
      - name: Docker login
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        run: docker image push ${{env.IMAGE_NAME}}